### ISSUE TITLE
[TYPE THE MC VERSION]: 1.7.10

### ISSUE THREAD

**Issue by RavenLP2** [quentin452/privates-minecraft-modpack#469]
### Modpack

Biggess Pack Cat Edition V0.85.78.2REUP

### Game log

[latest.log](https://github.com/quentin452/privates-minecraft-modpack/files/12642507/latest.log)

### Description

I have a problem on the loading screen when going to the texture loading area... the game crashes blaming certain mods, first it went to twilight forest, I deleted it and the problem went to Aether, then to Agricraft , etc. it was always switched to another mod when I eliminated the problem (it should be noted that before I had another crash-report because the "txloader" mod did not load well and I had to delete it, these problems occurred after that but before deleting txloader , it didn't even open the loading screen).

latest crash report: https://mclo.gs/nKskwIf

**Comment by quentin452** [comment]
Maybe try updating java?

**Comment by quentin452** [comment]
i see you have 6gb of ram try allocating more ram

**Comment by quentin452** [comment]
Should be fixed in V0.85.78.3 by disabling TEXTURE_OPTIMIZATIONS module in falsetweaks
